# Generated by Django 5.1.2 on 2024-12-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.CharField(choices=[('1', 'Одним вариантом'), ('2', 'Множественым вариантом ответа'), ('3', 'Открытый вопрос')], default='1', max_length=1),
        ),
    ]
