# Generated by Django 5.1.2 on 2024-12-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_responses_answer_responses_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='interiew_uuid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
