# Generated by Django 4.2.8 on 2024-12-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_responses_interiew_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey_questions',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='survey_questions',
            old_name='survey_id',
            new_name='survey',
        ),
    ]
