# Generated by Django 5.1.2 on 2024-12-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_question_id_survey_questions_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer_options',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='responses',
            old_name='survey_id',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='responses',
            old_name='survey_question_id',
            new_name='survey_question',
        ),
    ]
