# Generated by Django 5.1.2 on 2024-12-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_question_id_answer_options_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
