# Generated by Django 5.1.2 on 2024-12-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_responses_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='interiew_uuid',
        ),
    ]
